// <auto-generated />
using System;
using HousekeepingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HousekeepingAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250502000000_AddIsApprovedColumn")]
    partial class AddIsApprovedColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // The rest of the model will be updated when you run the migration
#pragma warning restore 612, 618
        }
    }
} 